import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


import Header from "./compnents/header/Header";
import Footer from "./compnents/footer/Footer";

const josefin = localFont({
  src: [
    {
      path: "../../public/fonts/Josefin.ttf",
      weight: "100",
      style: 'normal'
    }
  ]
})
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
