[workspace]
members = ["backend"]
default-members = ["backend"]
resolver = "2"


[workspace.dependencies]
rocket = { version = "0.5.1", features = ["json"]}

[workspace.package]
version = "0.1.0"
edition = "2021"