networks:
  dev:

services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "443:443"
      - "80:80"
      - "244:244"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - .
    networks:
      - dev

  rocket:
    build: 
      context: .
    command: bash -c "cargo run"
    networks:
      - dev