services:
  frontend:
    container_name: frontend
    image: noruffle/frontend:latest
    build:
      context: ./frontend
      dockerfile: next.Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    container_name: backend
    image: noruffle/backend:latest
    build:
      context: ./backend
      dockerfile: rust.Dockerfile
      args:
        - postgres://postgres:postgres@db5432/postgres
    ports:
      - 8080:8080
    
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}