[package]
name = "backend"
version = "0.1.0"
edition = "2021"



[dependencies]
rocket = { workspace = true }

[build-dependencies]
rocket.workspace = true

[dev-dependencies]
rocket.workspace = true
