name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          doctl compute ssh ${{ secrets.SERVER_ID }} --ssh-key-path ~/.ssh/id_rsa "ls -la"
          doctl compute ssh ${{ secrets.SERVER_ID }} --ssh-key-path ~/.ssh/id_rsa "docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker-compose pull && docker-compose up -d"


    #  - name: Install Docker Compose
    #    run: |
    #      sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #      sudo chmod +x /usr/local/bin/docker-compose
    #      docker-compose --version

    #  - name: Build and push Docker images using Docker Compose
    #    run: docker-compose -f docker-compose.yml build && docker-compose -f docker-compose.yml push

    #  - name: Deploy to server
    #    env:
    #      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #      SERVER_IP: ${{ secrets.SERVER_IP }}
    #      USER: ${{ secrets.SERVER_USER }}
    #    run: |
    #      echo "$SSH_PRIVATE_KEY" > private_key
    #      chmod 600 private_key
    #      scp -i private_key -o StrictHostKeyChecking=no -r ./deploy.sh $USER@$SERVER_IP:/tmp/
    #      ssh -i private_key -o StrictHostKeyChecking=no $USER@$SERVER_IP 'bash /tmp/deploy.sh'
