name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          services: |
            backend
            frontend

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: SSH into Droplet and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker-compose pull
            docker-compose up -d
          EOF
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    #  - name: Install Docker Compose
    #    run: |
    #      sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #      sudo chmod +x /usr/local/bin/docker-compose
    #      docker-compose --version

    #  - name: Build and push Docker images using Docker Compose
    #    run: docker-compose -f docker-compose.yml build && docker-compose -f docker-compose.yml push

    #  - name: Deploy to server
    #    env:
    #      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #      SERVER_IP: ${{ secrets.SERVER_IP }}
    #      USER: ${{ secrets.SERVER_USER }}
    #    run: |
    #      echo "$SSH_PRIVATE_KEY" > private_key
    #      chmod 600 private_key
    #      scp -i private_key -o StrictHostKeyChecking=no -r ./deploy.sh $USER@$SERVER_IP:/tmp/
    #      ssh -i private_key -o StrictHostKeyChecking=no $USER@$SERVER_IP 'bash /tmp/deploy.sh'
