name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up SSH
        uses: shimatsu/setup-ssh@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     - name: Deploy to Droplet
        run: |
          doctl compute ssh ${{ secrets.DROPLET_ID }} -- "ls -la && docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && docker-compose pull && docker-compose up -d"