name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up SSH
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          IP: ${{ secrets.SERVER_IP }}
        uses: shimataro/ssh-key-action@v2
        with:
          key: $KEY
          known_hosts: $IP
      - name: Deploy
        env:
          USER: ${{ secrets.SERVER_USER }}
          IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh-keyscan $IP >> /root/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $USER@$IP "cd /var/www/html && git pull"
